---

  - name: start noaa
    service:
      name: noaa
      state: started
    become: true

  - name: restart noaa
    service:
      name: noaa
      state: restarted
      enabled: yes
    become: true
